CREATE TABLE IF NOT EXISTS tracks (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	uuid UUID NOT NULL DEFAULT UUID(),
	name TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (name)
);
