CREATE TABLE IF NOT EXISTS tracks (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	uuid VARCHAR(32) NOT NULL DEFAULT (UUID()),
	name TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
	UNIQUE (name(255))
);
